ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS morning_end TEXT DEFAULT '12:00',
ADD COLUMN IF NOT EXISTS afternoon_end TEXT DEFAULT '18:00',
ADD COLUMN IF NOT EXISTS evening_end TEXT DEFAULT '24:00';
